#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE="$SCRIPT_DIR/base.kdl"

render_config() {
  local platform="$1"
  local overlay="$SCRIPT_DIR/overlay.${platform}.kdl"
  local output="$SCRIPT_DIR/config.${platform}.kdl"

  {
    printf '%s\n' '// Generated by dotfiles/zellij/render.sh. Do not edit directly.'
    printf '\n'
    cat "$BASE"
    printf '\n'
    cat "$overlay"
    printf '\n'
  } > "$output"
}

render_config "macos"
render_config "linux"
